sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "030419"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7FnT1eWkiVYFNd5aM1
    access-key-secret: cx54ZQp6BosMIHREqZ6vlK77OYmXHC
    bucket-name: java-cys-oss
    region: cn-beijing

